name: artemis_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  artemis: ^7.9.0-beta
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  gql: '>=0.12.3 <1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  artemis: ^7.9.0-beta
  build_runner: ^2.2.1
  json_serializable: ^6.3.2

flutter:
  uses-material-design: true
